function dydt=networkODE(t,y,params) 
% Set of logic-based ODEs
% Automatically generated by Netflux on 06-Dec-2021


% Assign names for parameters 
[rpar,tau,ymax,speciesNames]=params{:}; 
GLU = 1; 
LPS = 2; 
AGE = 3; 
VEGFRec1 = 4; 
VEGFRec2 = 5; 
VEGFamRNA = 6; 
RAGEec = 7; 
RAGE = 8; 
TLR4 = 9; 
NADPH = 10; 
NADPHec = 11; 
ROSec = 12; 
ROS = 13; 
PI3K = 14; 
AKT = 15; 
PI3Kec = 16; 
AKTec = 17; 
NFKBec = 18; 
NFKB = 19; 
NO = 20; 
ONOO = 21; 
eNOS = 22; 
IL6 = 23; 
TNFa = 24; 
IL1b = 25; 
PLC = 26; 
VEGFa = 27; 
pJunc = 28; 
Calcium = 29; 
GapWidth = 30; 

dydt = zeros(30,1); 

% time-dependent glucose (in vitro cell culture)
dydt(GLU) = (rpar(1,1)*ymax(GLU) - y(GLU))/tau(GLU);
dydt(LPS) = (rpar(1,2)*ymax(LPS) - y(LPS))/tau(LPS); 
dydt(AGE) = (act(y(GLU),rpar(:,4))*ymax(AGE) - y(AGE))/tau(AGE); 
dydt(VEGFRec1) = (act(y(VEGFa),rpar(:,19))*ymax(VEGFRec1) - y(VEGFRec1))/tau(VEGFRec1); 
dydt(VEGFRec2) = (act(y(VEGFa),rpar(:,20))*ymax(VEGFRec2) - y(VEGFRec2))/tau(VEGFRec2); 
dydt(VEGFamRNA) = (act(y(NFKB),rpar(:,16))*ymax(VEGFamRNA) - y(VEGFamRNA))/tau(VEGFamRNA); 
dydt(RAGEec) = (act(y(AGE),rpar(:,21))*ymax(RAGEec) - y(RAGEec))/tau(RAGEec); 
dydt(RAGE) = (act(y(AGE),rpar(:,5))*ymax(RAGE) - y(RAGE))/tau(RAGE); 
dydt(TLR4) = (act(y(LPS),rpar(:,3))*ymax(TLR4) - y(TLR4))/tau(TLR4); 
dydt(NADPH) = (act(y(RAGE),rpar(:,6))*ymax(NADPH) - y(NADPH))/tau(NADPH); 
dydt(NADPHec) = (act(y(RAGEec),rpar(:,22))*ymax(NADPHec) - y(NADPHec))/tau(NADPHec); 
dydt(ROSec) = (OR(act(y(NADPHec),rpar(:,25)),act(y(eNOS),rpar(:,34)))*ymax(ROSec) - y(ROSec))/tau(ROSec); 
dydt(ROS) = (OR(act(y(NADPH),rpar(:,9)),act(y(PI3K),rpar(:,11)))*ymax(ROS) - y(ROS))/tau(ROS); 
dydt(PI3K) = (act(y(TLR4),rpar(:,8))*ymax(PI3K) - y(PI3K))/tau(PI3K); 
dydt(AKT) = (act(y(PI3K),rpar(:,10))*ymax(AKT) - y(AKT))/tau(AKT); 
dydt(PI3Kec) = (OR(act(y(VEGFRec2),rpar(:,23)),act(y(VEGFRec1),rpar(:,24)))*ymax(PI3Kec) - y(PI3Kec))/tau(PI3Kec); 
dydt(AKTec) = (act(y(PI3Kec),rpar(:,26))*ymax(AKTec) - y(AKTec))/tau(AKTec); 
dydt(NFKBec) = (OR(act(y(PLC),rpar(:,29)),act(y(ROSec),rpar(:,30)))*ymax(NFKBec) - y(NFKBec))/tau(NFKBec); 
dydt(NFKB) = (OR(AND(rpar(:,7),act(y(TLR4),rpar(:,7)),act(y(ROS),rpar(:,7))),act(y(AKT),rpar(:,13)))*ymax(NFKB) - y(NFKB))/tau(NFKB); 
dydt(NO) = (OR(act(y(eNOS),rpar(:,33)),act(y(Calcium),rpar(:,40)))*ymax(NO) - y(NO))/tau(NO); %(AND(rpar(:,33),act(y(eNOS),rpar(:,33)),act(y(Calcium),rpar(:,33)))*ymax(NO) - y(NO))/tau(NO); % 
dydt(ONOO) = (AND(rpar(:,35),act(y(ROSec),rpar(:,35)),act(y(NO),rpar(:,35)))*ymax(ONOO) - y(ONOO))/tau(ONOO); 
dydt(eNOS) = (act(y(AKTec),rpar(:,27))*ymax(eNOS) - y(eNOS))/tau(eNOS); 
dydt(IL6) = (OR(act(y(NFKB),rpar(:,14)),act(y(NFKBec),rpar(:,31)))*ymax(IL6) - y(IL6))/tau(IL6); 
dydt(TNFa) = (OR(act(y(NFKBec),rpar(:,12)),act(y(NFKB),rpar(:,15)))*ymax(TNFa) - y(TNFa))/tau(TNFa); 
dydt(IL1b) = (OR(act(y(NFKB),rpar(:,18)),act(y(NFKBec),rpar(:,32)))*ymax(IL1b) - y(IL1b))/tau(IL1b); 
dydt(PLC) = (act(y(VEGFRec1),rpar(:,28))*ymax(PLC) - y(PLC))/tau(PLC); 
dydt(VEGFa) = (act(y(VEGFamRNA),rpar(:,17))*ymax(VEGFa) - y(VEGFa))/tau(VEGFa);
dydt(Calcium) = (OR(inhib(y(NO),rpar(:,36)),act(y(PLC),rpar(:,37)))*ymax(Calcium) - y(Calcium))/tau(Calcium);

  
if params{1}(1,1) == 0 && params{1}(1,2) == 0
    dydt(pJunc) = 0;
    dydt(GapWidth) = 0;
else
    dydt(pJunc) = (act(y(Calcium),rpar(:,38))*ymax(pJunc) - y(pJunc))/tau(pJunc); 
    dydt(GapWidth) = (act(y(pJunc),rpar(:,39))*ymax(GapWidth) - y(GapWidth))/(tau(GapWidth));
    
end
end
% utility functions 
function fact = act(x,rpar) 
% hill activation function with parameters w (weight), n (Hill coeff), EC50 
    w = rpar(1); 
    n = rpar(2); 
    EC50 = rpar(3); 
    beta = (EC50.^n - 1)./(2*EC50.^n - 1); 
    K = (beta - 1).^(1./n); 
    fact = w.*(beta.*x.^n)./(K.^n + x.^n); 
    if fact>w,                 % cap fact(x)<= 1 
        fact = w; 
    end
end

function finhib = inhib(x,rpar) 
% inverse hill function with parameters w (weight), n (Hill coeff), EC50 
    finhib = rpar(1) - act(x,rpar);
end

function z = OR(x,y) 
% OR logic gate 
    z = x + y - x*y;
end

function z = AND(rpar,varargin) 
% AND logic gate, multiplying all of the reactants together 
    w = rpar(1); 
    if w == 0, 
        z = 0; 
    else 
        v = cell2mat(varargin); 
        z = prod(v)/w^(nargin-2);  
    end 
end

